version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    env_file: .env.docker
    container_name: hn_parser
    expose:
      - 8000
    depends_on:
      - sqlite3
      - celery
      - rabbit
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/code
  celery:
    image: celery:3.1.23
  rabbit:
    image: rabbitmq:3.6.9-alpine
  nginx:
    build: ./nginx
    volumes:
      - .:/code
    ports:
      - 1337:80
    depends_on:
      - web
